name: Android CI (debug)

on: # i from Indonesia 
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:  # Memungkinkan menjalankan workflow secara manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'  # Inisialisasi submodule jika ada

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3
        with:
          packages: 'platforms;android-34 build-tools;34.0.0 ndk;24.0.8215888 cmake;3.22.1'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Apply patches
        run: |
          if [ -d "patches" ] && [ -n "$(ls -A patches/*.patch 2>/dev/null)" ]; then
            echo "Applying patches..."
            git apply patches/*.patch
          else
            echo "No patches to apply."
          fi

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Build Debug APK
        run: ./gradlew assembleDebug

#      - name: Build Release APK
#        run: ./gradlew assembleRelease

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: winlator-debug
          path: app/build/outputs/apk/debug/*.apk

#      - name: Upload Release APK
#        uses: actions/upload-artifact@v4
#        with:
#          name: winlator-release-unsigned
#          path: app/build/outputs/apk/release/*.apk
